### ISSUE TITLE
А надо ли здесь else?

### ISSUE THREAD

**Issue by mp0120** [Maltsau/Study#4]
https://github.com/Maltsau/Study/blob/73dbe7eb56ae705d8f9143a1691249e461570c94/script.js#L72

**Comment by Maltsau** [comment]
Сделал вот так:
function isStringLength (str,min,max){
    if (typeof(str)==`string`) return isNumberInRange(str.length,min,max)
    else return false;
}
Теперь проверяет на то, что это строка, и в противном случае возвращает false (без else - undefined). А до этого возвращала undefined во всех случаях, когда аргумент не строка. Действительно, else там роли не играл, но задача была не решена)
